#vars-file-yaml

- name: vars-files information
  hosts: web
  vars_files:
      -vars.yaml
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "{Hi iam learning Course is:{{COURSE}},Duration is:{{DURATION}},Trainer is:{{TRAINER}}}"