# variables from promt

- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  - name: DURATION
    prompt: please enter the course duration
    private: false
  - name: TRAINER
    prompt: please enter the course trainer
    private: false 
  tasks:
  - name: print variables from promt
    ansible.builtin.debug:
      msg: "Hi,iam Learning Course is:{{COURSE}}, Duration is:{{DURATION}}, Trainer is:{{TRAINER}}"
      