# print the given number is leesthan 10 are not

- name: given number is lessthan 10 are not
  hosts: local
  connection: local
  # vars_prompt:
  # - name: my_number
  #   prompt: please enter the number 
  #   private: false
  vars:
    my_number: 8
  tasks:
  - name: given numbeis less than  10
    ansible.builtin.debug:
     msg: "The given number {{my_number}} is less than 10"
    when: my_number is{{my_number}} < 10 

  - name: given number is greater than are equal to 10
    ansible.builtin.debug:
    msg: "The given number {{my_number}} is greater than 10"
    when: my_number is{{my_number}} > 10
