# print the given number is leesthan 10 are not

- name: given number is lessthan 10 are not
  hosts: local
  connection: local
  # vars_prompt:
  # - name: my_number
  #   prompt: please enter the number 
  #   private: false
  vars:
    my_number: 22
  tasks:
  - name: print this if less than  10
    ansible.builtin.debug:
     msg: "The given number {{my_number}} is less than 10"
    when: my_number < 10 

  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
     msg: "The given number {{my_number}} is greater than or equal to 10"
    when: my_number >= 10
