# install package

- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      msg: "{{ item }}"
      state: present
    loop:
      - nginx
      - mysql
      - postfix
      - httpd
