# install packages

- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: install packages by useing loops
    ansible.builtin.package:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
      - {name:'nginx', state:'present'}
      - {name:'mysql', state:'absent'}
      - {name:'postfix', state:'present'}
      - {name:'httpd', state:'absent'} 
