# filters/functions

- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('Ansible') }}"
    
  - name: convert to uppercase
    vars:
      greeting: "hello suresh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  -  name: covert to lowercase
     vars:
      greeting: "HELLO RAMESH,HOW ARE YOU"
     ansible.builtin.debug:
       msg: "{{ greeting | lower }}"

  - name: get the unique numbers
    vars:
      numbers: [1,2,3,4,6,7,19,35,9,29,10]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"

  - name: get the min and max
    vars:
      numbers: [1,2,3,5,12,23,67,22,9,0,6,11,33,7,99,8,77,10]
    ansible.builtin.debug:
      msg: " min: {{ numbers | min }}, max: {{ numbers | max }}" 

  - name: covnert map to list
    vars:
      course:
        name: "Devops with Aws"
        duration: 180 Days
        trainer: Suresh
    ansible.builtin.debug:
      msg: " {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - { 'key': "name",'value': "Devops with Aws" }
      - { "key": "duration","value": "180 Days" }
      - { "key": "trainer", "value": "Suresh" }
    ansible.builtin.debug:
      msg: " {{ course | items2dict }} "  


