# filters/functions

- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('Ansible') }}"
    
  - name: convert to uppercase
    vars:
      greeting: "hello suresh"
    ansible.duiltin.debug:
      msg: "{{ greeting | upper }}"

  -  name: covert to lowercase
     vars:
      greeting: "HELLO RAMESH,HOW ARE YOU"
     ansible.builtin.debug:
       msg: "{{ greeting | lower }}"


