# command vs shell

- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt # shell login to server and execute the commands
    # ansible.builtin.command: -->command module just issue the commands only.

  - name: check the process
    ansible.builtin.command: ps -ef | grep
    register: output